-- AlterTable
ALTER TABLE "Admin" ALTER COLUMN "super" SET DEFAULT false;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
